typeset -U path

export DO_NOT_TRACK=1
export VP_HOME="$HOME/.vite-plus"
export VP_NO_UPDATE_CHECK=1
[[ -z "$EDITOR" ]] && export EDITOR="code --wait"

path=(
  "$HOME/.local/bin"
  "$HOME/.cargo/bin"
  "$HOME/go/bin"
  "$HOME/.opencode/bin"
  "$HOME/.lmstudio/bin"
  $path
)
export PATH

[[ -f "$HOME/.zshenv.host" ]] && source "$HOME/.zshenv.host"
[[ -f "$VP_HOME/env" ]] && source "$VP_HOME/env"
