setopt AUTO_CD AUTO_PUSHD PUSHD_IGNORE_DUPS PUSHD_MINUS INTERACTIVE_COMMENTS
setopt AUTO_MENU COMPLETE_IN_WORD ALWAYS_TO_END NO_FLOW_CONTROL
setopt EXTENDED_HISTORY HIST_EXPIRE_DUPS_FIRST HIST_IGNORE_DUPS HIST_IGNORE_SPACE
setopt HIST_VERIFY SHARE_HISTORY

HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000

if [[ -n "$HOMEBREW_PREFIX" ]]; then
  fpath+=("$HOMEBREW_PREFIX/share/zsh-completions" "$HOMEBREW_PREFIX/share/zsh/site-functions")
fi
[[ -d "$HOME/.zsh/completions" ]] && fpath+=("$HOME/.zsh/completions")

autoload -U compinit && compinit

zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' use-cache yes
zstyle ':completion:*' cache-path "$HOME/.zsh/cache"
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'

for _autosuggestions in \
  "${HOMEBREW_PREFIX:-/dev/null}/share/zsh-autosuggestions/zsh-autosuggestions.zsh" \
  "/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"; do
  [[ -f "$_autosuggestions" ]] && source "$_autosuggestions" && break
done
unset _autosuggestions
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#7a8194,bold,underline"

alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -- -='cd -'
alias d='dirs -v | head -10'
alias ls='eza -a'
alias l='eza -la'
alias vsc='code -r'
alias q='exit'
alias cat='bat'
alias c='clear'
alias g='git'
alias lg='lazygit'

tmpcd() {
  local directory
  directory="$(mktemp -d)" || return
  cd "$directory" || return
}

bp() {
  case "$1" in
    clone)
      if [[ "$2" == "--help" ]]; then
        print "usage: bp clone <owner/repo|url>"
        return 0
      fi

      if (( $# != 2 )); then
        print -u2 "usage: bp clone <owner/repo|url>"
        return 2
      fi

      local repo_info owner_repo ssh_url destination
      repo_info="$(gh repo view "$2" --json nameWithOwner,sshUrl --jq '.nameWithOwner + "\t" + .sshUrl')" || return
      owner_repo="${repo_info%%$'\t'*}"
      ssh_url="${repo_info#*$'\t'}"
      destination="$HOME/Projects/$owner_repo"

      mkdir -p "${destination:h}" || return
      git clone "$ssh_url" "$destination"
      ;;
    *)
      print -u2 "usage: bp clone <owner/repo|url>"
      return 2
      ;;
  esac
}

command -v starship > /dev/null && eval "$(starship init zsh)"
command -v zoxide > /dev/null && eval "$(zoxide init zsh)"
command -v atuin > /dev/null && eval "$(atuin init zsh)"
command -v zsh-patina > /dev/null && eval "$(zsh-patina activate)"

set_title() {
  print -Pn "\e]0;%~\a"
}
precmd_functions+=(set_title)

[[ -f "$HOME/.zshrc.host" ]] && source "$HOME/.zshrc.host"
