/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardAppsRouteImport } from './routes/_dashboard.apps'
import { Route as DashboardDeviceRouteImport } from './routes/_dashboard.device'
import { Route as DashboardDevicesRouteImport } from './routes/_dashboard.devices'
import { Route as DashboardSessionsRouteImport } from './routes/_dashboard.sessions'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsRoute = DashboardAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeviceRoute = DashboardDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevicesRoute = DashboardDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsRoute = DashboardSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/consent': typeof ConsentRoute
  '/error': typeof ErrorRoute
  '/apps': typeof DashboardAppsRoute
  '/device': typeof DashboardDeviceRoute
  '/devices': typeof DashboardDevicesRoute
  '/sessions': typeof DashboardSessionsRoute
}
export interface FileRoutesByTo {
  '/consent': typeof ConsentRoute
  '/error': typeof ErrorRoute
  '/apps': typeof DashboardAppsRoute
  '/device': typeof DashboardDeviceRoute
  '/devices': typeof DashboardDevicesRoute
  '/sessions': typeof DashboardSessionsRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/consent': typeof ConsentRoute
  '/error': typeof ErrorRoute
  '/_dashboard/apps': typeof DashboardAppsRoute
  '/_dashboard/device': typeof DashboardDeviceRoute
  '/_dashboard/devices': typeof DashboardDevicesRoute
  '/_dashboard/sessions': typeof DashboardSessionsRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/consent' | '/error' | '/apps' | '/device' | '/devices' | '/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/consent' | '/error' | '/apps' | '/device' | '/devices' | '/sessions' | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/consent'
    | '/error'
    | '/_dashboard/apps'
    | '/_dashboard/device'
    | '/_dashboard/devices'
    | '/_dashboard/sessions'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  ErrorRoute: typeof ErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps': {
      id: '/_dashboard/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof DashboardAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/device': {
      id: '/_dashboard/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DashboardDeviceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/devices': {
      id: '/_dashboard/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DashboardDevicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sessions': {
      id: '/_dashboard/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof DashboardSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAppsRoute: typeof DashboardAppsRoute
  DashboardDeviceRoute: typeof DashboardDeviceRoute
  DashboardDevicesRoute: typeof DashboardDevicesRoute
  DashboardSessionsRoute: typeof DashboardSessionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppsRoute: DashboardAppsRoute,
  DashboardDeviceRoute: DashboardDeviceRoute,
  DashboardDevicesRoute: DashboardDevicesRoute,
  DashboardSessionsRoute: DashboardSessionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  ConsentRoute: ConsentRoute,
  ErrorRoute: ErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
